# Lab Assignment 1: Rock, Paper, Scissors

## Write and Run Your Own Code to Implement a Rock-Paper-Scissors Model

In [1]:
# Library Declarations
import numpy as np
import random

np.random.seed(0)
random.seed(0)


In [2]:
# Data extraction here: extract the data from the txt file to python input
# One suggestion is using integers 0,1,2 for rock paper scissor
# and using CPU guess, your guess and score (1 if you win; -1 if you lose; 0 for draw) as possible data
demo_data = np.loadtxt(r"./demo_data.txt", dtype=int) .reshape(-1,3)
print("The data in this file has been stored in a NumPy array of size {}.".format(demo_data.shape))
print(demo_data)

The data in this file has been stored in a NumPy array of size (5, 3).
[[ 0  1  1]
 [ 0  2 -1]
 [ 1  0 -1]
 [ 2  0  1]
 [ 0  0  0]]


In [ ]:
def rock_paper_scissor(history=None, last_choice=None):
    # Weigh opponent and self totals with gradient weighting
    opp_totals = {}
    self_totals = {}
    total_weight = 0
    
    # Count moves with gradient weights (most recent moves get higher weight)

    for i in range(len(history)):
        position = i  # Position from oldest 
        moves_ago = len(history) - 1 - position  
        
        # Weights based on how recent moves are 
        if moves_ago < 5:
            weight = 5
        elif moves_ago < 10:
            weight = 4
        elif moves_ago < 30:
            weight = 3  
        elif moves_ago < 50:
            weight = 2 
        else:
            weight = 1  
        
        # Now apply weight
        round = history[i]
        opp = round[0]
        self = round[1]
        

        opp_totals[opp] = opp_totals.get(opp, 0) + weight
        self_totals[self] = self_totals.get(self, 0) + weight
        total_weight += weight

    opp_ratio = []
    self_ratio = []

    # Weighted ratios
    for i in [0, 1, 2]:  
        opp_ratio.append(opp_totals.get(i, 0) / total_weight)  
        self_ratio.append(self_totals.get(i, 0) / total_weight)

    opp_ratio = np.array(opp_ratio)
    self_ratio = np.array(self_ratio)

    res = []

    #rock, paper, scissor
    res.append(opp_ratio[2] + self_ratio[1])  
    res.append(opp_ratio[0] + self_ratio[2])  
    res.append(opp_ratio[1] + self_ratio[0])  
    
    res_array = np.array(res)
    if res_array.sum() == 0:
        # Fallback to uniform probabilities
        probabilities = np.array([1/3, 1/3, 1/3])
    else:
        probabilities = res_array / res_array.sum()
    
    print(probabilities)

    return np.random.choice([0, 1, 2], p=probabilities)

In [33]:
# Load training data
history = np.loadtxt(r"./training.txt", dtype=int).reshape(-1,3)
print(f"Loaded training data with {history.shape[0]} rounds.")

# Use the algorithm to predict next move
print(f'Algorithm says you should choose: {rock_paper_scissor(history)}')

Loaded training data with 100 rounds.
[0.32 0.38 0.3 ]
Algorithm says you should choose: 1


## What to Submit?

**Note: This is the first assignment, designed to help you get familiar with the GitHub workflow.**

**For this assignment only**, please submit a `.zip` file containing:
1. Your training data in `training.txt`.
2. Your model evaluation data.
3. A brief write-up describing your algorithm in a couple of sentences, including figures if necessary (your design on paper).
4. Finally, please individually briefly reflect on your experience in a couple of sentences. What are you taking away from this lab?

**Starting from Assignment 2**: Next week, we will release a Google Sheet assigning each student a Lab TA. From Assignment 2 onwards, you will need to:
- Submit a link to your GitHub repository (instead of a .zip file)
- Add your assigned Lab TA as a collaborator to your repository, or they won't be able to grade your work! 